package view;


import java.awt.HeadlessException;
import java.awt.event.WindowAdapter;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sharma parul
 */
public class AddTaskMenuItem extends javax.swing.JInternalFrame  {

    /**
     * Creates new form edittask
     */
    PreparedStatement pst;
    String resource_select;
    String enable;
    String value1;
    String selection;
    String predecessor_select;
    String predecessor;
    String successor_select;
    String successor;
    private String Tasktype;
     Connection con1;
     ResultSet rs=null;
     String name;
   public AddTaskMenuItem() {
        initComponents();
    }

    private AddTaskMenuItem(JFrame jFrame, boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        simpletask = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Description = new javax.swing.JTextField();
        StartTime = new javax.swing.JTextField();
        Duration = new javax.swing.JTextField();
        EndTime = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Name = new javax.swing.JTextField();
        PercentComplete = new javax.swing.JTextField();
        Deliverable = new javax.swing.JTextField();
        Resource = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        projectid = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        taskid = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        subtasks = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        predecessors = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        successors = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();

        jInternalFrame1.setClosable(true);
        jInternalFrame1.setMaximizable(true);
        jInternalFrame1.setResizable(true);
        jInternalFrame1.setVisible(true);

        simpletask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpletaskActionPerformed(evt);
            }
        });

        jLabel3.setText("Name");

        jLabel4.setText("Description");

        jLabel5.setText("Start Time");

        jLabel6.setText("Duration");

        jLabel7.setText("End Time");

        jLabel8.setText("Resource");

        jLabel9.setText("Percent Complete");

        Description.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DescriptionActionPerformed(evt);
            }
        });

        jLabel10.setText("Deliverable URL");

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameActionPerformed(evt);
            }
        });

        Resource.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item" }));
        Resource.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResourceActionPerformed(evt);
            }
        });

        jLabel11.setText("ProjectId");

        jLabel1.setText("TaskId");

        jLabel12.setText("SubTasks");

        subtasks.setModel(new javax.swing.DefaultComboBoxModel(new String[]{"Item"}));
        subtasks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subtasksActionPerformed(evt);
            }
        });

        jLabel13.setText("Predecessors");

        predecessors.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item" }));
        predecessors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                predecessorsActionPerformed(evt);
            }
        });

        jLabel14.setText("Successors");

        successors.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item" }));
        successors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                successorsActionPerformed(evt);
            }
        });

        jLabel15.setText("SimpleTask");

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Resource, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(simpletask))
                    .addComponent(Description, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                    .addComponent(StartTime)
                    .addComponent(Duration)
                    .addComponent(EndTime)
                    .addComponent(Name)
                    .addComponent(PercentComplete)
                    .addComponent(projectid, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(taskid, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(437, Short.MAX_VALUE))
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(49, 49, 49)
                        .addComponent(subtasks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(jLabel13)
                        .addGap(58, 58, 58)
                        .addComponent(predecessors, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(jLabel14)
                        .addGap(61, 61, 61)
                        .addComponent(successors, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(116, 116, 116)
                        .addComponent(Deliverable, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(220, Short.MAX_VALUE))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(projectid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(taskid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15)
                    .addComponent(simpletask))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Description, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(StartTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Duration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(EndTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Resource, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(PercentComplete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(subtasks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(predecessors, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(successors, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Deliverable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void successorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_successorsActionPerformed
        try
    {
    
     Class.forName("com.mysql.jdbc.Driver");
     System.out.println("connected");
     con1 = DriverManager.getConnection("jdbc:mysql://localhost:3306/mydb","root","root");
     String query="select Name from tasks";
     pst=con1.prepareStatement(query);
     rs=pst.executeQuery();
     while(rs.next())
     {
          String result=rs.getString("Name");
          successors.addItem(result);
     }
   }    catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(AddTaskMenuItem.class.getName()).log(Level.SEVERE, null, ex);
        }
   
    }//GEN-LAST:event_successorsActionPerformed

    private void predecessorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_predecessorsActionPerformed
        try
    {
    
     Class.forName("com.mysql.jdbc.Driver");
     System.out.println("connected");
     con1 = DriverManager.getConnection("jdbc:mysql://localhost:3306/mydb","root","root");
     String query="select Name from tasks";
     pst=con1.prepareStatement(query);
     rs=pst.executeQuery();
     while(rs.next())
     {
          String result=rs.getString("Name");
          predecessors.addItem(result);
     }
   }    catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(AddTaskMenuItem.class.getName()).log(Level.SEVERE, null, ex);
        }
   
       
       
        
    }//GEN-LAST:event_predecessorsActionPerformed

    private void subtasksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subtasksActionPerformed
        
    try
    {
    
     Class.forName("com.mysql.jdbc.Driver");
     System.out.println("connected");
     con1 = DriverManager.getConnection("jdbc:mysql://localhost:3306/mydb","root","root");
     String query="select Name from tasks";
     pst=con1.prepareStatement(query);
     rs=pst.executeQuery();
     while(rs.next())
     {
          String result=rs.getString("Name");
          subtasks.addItem(result);
     }
   }    catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(AddTaskMenuItem.class.getName()).log(Level.SEVERE, null, ex);
        }
   
       
       
        
    }//GEN-LAST:event_subtasksActionPerformed

    private void ResourceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResourceActionPerformed
        
    try
    {
    
     Class.forName("com.mysql.jdbc.Driver");
     System.out.println("connected");
     con1 = DriverManager.getConnection("jdbc:mysql://localhost:3306/mydb","root","root");
     String query="select Name from resources";
     pst=con1.prepareStatement(query);
     rs=pst.executeQuery();
     while(rs.next())
     {
          String result=rs.getString("Name");
          Resource.addItem(result);
     }
   }    catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(AddTaskMenuItem.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_ResourceActionPerformed

    private void NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            System.out.println("connected");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mydb","root","root");
            value1=enable;
            selection=resource_select;
          
            predecessor=predecessor_select;
            successor=successor_select;
            String query;
            query = "Insert into tasks(ProjectId,TaskId,TaskType,Name,Description,StartTime,Duration,EndTime,Resource,PercentComplete,SubTasks,Predecessors,Successors,Deliverable)values(?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
            pst = con.prepareStatement(query);
            pst.setString(1,projectid.getText());
            pst.setString(2,taskid.getText());
            pst.setString(3,Tasktype);
            pst.setString(4,Name.getText());
            pst.setString(5,Description.getText());
            pst.setString(6,StartTime.getText());
            pst.setString(7,Duration.getText());
            pst.setString(8,EndTime.getText());
            pst.setString(9,selection);
            pst.setString(10,PercentComplete.getText());
            pst.setString(11, (String) subtasks.getSelectedItem());
            pst.setString(12,predecessor);
            pst.setString(13,successor);
            pst.setString(14,Deliverable.getText());

            pst.execute();
            JOptionPane.showMessageDialog(null,"saved");
        }
        catch(SQLException | HeadlessException e)
        {
            JOptionPane.showMessageDialog(null, e);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CreateProjectMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void DescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DescriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DescriptionActionPerformed

    private void simpletaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpletaskActionPerformed
        Tasktype="simpletask";

    }//GEN-LAST:event_simpletaskActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddTaskMenuItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddTaskMenuItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddTaskMenuItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddTaskMenuItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddTaskMenuItem dialog = new AddTaskMenuItem(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Deliverable;
    private javax.swing.JTextField Description;
    private javax.swing.JTextField Duration;
    private javax.swing.JTextField EndTime;
    private javax.swing.JTextField Name;
    private javax.swing.JTextField PercentComplete;
    private javax.swing.JComboBox Resource;
    private javax.swing.JTextField StartTime;
    private javax.swing.JButton jButton1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox predecessors;
    private javax.swing.JTextField projectid;
    private javax.swing.JCheckBox simpletask;
    private javax.swing.JComboBox subtasks;
    private javax.swing.JComboBox successors;
    private javax.swing.JTextField taskid;
    // End of variables declaration//GEN-END:variables

    private void addWindowListener(WindowAdapter windowAdapter) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
